//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bank.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bank.Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card was created..
        /// </summary>
        internal static string CCCreated {
            get {
                return ResourceManager.GetString("CCCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card&apos;s ID is incorrect..
        /// </summary>
        internal static string CCIdNull {
            get {
                return ResourceManager.GetString("CCIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This card number is already exist..
        /// </summary>
        internal static string CCNumExist {
            get {
                return ResourceManager.GetString("CCNumExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creadit card information was updated..
        /// </summary>
        internal static string CCUpdt {
            get {
                return ResourceManager.GetString("CCUpdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer created..
        /// </summary>
        internal static string CusCreat {
            get {
                return ResourceManager.GetString("CusCreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer&apos;s ID is incorrect..
        /// </summary>
        internal static string CusIdNull {
            get {
                return ResourceManager.GetString("CusIdNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer information was updated..
        /// </summary>
        internal static string CusUpdt {
            get {
                return ResourceManager.GetString("CusUpdt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction amount should be above zero..
        /// </summary>
        internal static string IncAmount {
            get {
                return ResourceManager.GetString("IncAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This login is already exist..
        /// </summary>
        internal static string LogExist {
            get {
                return ResourceManager.GetString("LogExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter login and password..
        /// </summary>
        internal static string NoLogPass {
            get {
                return ResourceManager.GetString("NoLogPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter card number and PIN..
        /// </summary>
        internal static string NoNumPin {
            get {
                return ResourceManager.GetString("NoNumPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create at least two credit cards..
        /// </summary>
        internal static string NotEnCards {
            get {
                return ResourceManager.GetString("NotEnCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is incorrect..
        /// </summary>
        internal static string PassDontMatch {
            get {
                return ResourceManager.GetString("PassDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current PIN is incorrect..
        /// </summary>
        internal static string PinsDontMatch {
            get {
                return ResourceManager.GetString("PinsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction was generated automatically..
        /// </summary>
        internal static string RndTran {
            get {
                return ResourceManager.GetString("RndTran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select different credit cards..
        /// </summary>
        internal static string SelectDifCards {
            get {
                return ResourceManager.GetString("SelectDifCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions not possible. Not enough funds on all card accounts..
        /// </summary>
        internal static string TranAllCCOutOfFunds {
            get {
                return ResourceManager.GetString("TranAllCCOutOfFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction failed. Error occurred: .
        /// </summary>
        internal static string TranFail {
            get {
                return ResourceManager.GetString("TranFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction was successfull..
        /// </summary>
        internal static string TranOk {
            get {
                return ResourceManager.GetString("TranOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough funds on card account..
        /// </summary>
        internal static string TranOutOfFunds {
            get {
                return ResourceManager.GetString("TranOutOfFunds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions were successfully generated..
        /// </summary>
        internal static string TransGenDone {
            get {
                return ResourceManager.GetString("TransGenDone", resourceCulture);
            }
        }
    }
}
